# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["nodejs", "php81", "php81Extensions.pdo", "php81Extensions.pdo_mysql", "php81Extensions.mbstring", "php81Extensions.xml", "php81Extensions.bcmath", "php81Extensions.tokenizer", "php81Extensions.json", "php81Extensions.curl", "php81Extensions.zip", "php81Extensions.openssl"]

[phases.install]
cmds = [
    "cd backend && composer install --optimize-autoloader --no-dev",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cd backend && php artisan config:cache && php artisan route:cache && php artisan view:cache"
]

[start]
cmd = "cd backend && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"